spring.application.name=teamverwaltung
server.servlet.context-path=/teamverwaltung
server.port=8888

server.servlet.session.timeout=15m
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true
# server.servlet.session.cookie.same-site =strict

#Show or not log for each sql query
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
# Hybernate ddl auto (create, create-drop, update): with "create-drop" the database
# schema will be automaticly created afresh for every start of application
# spring.jpa.hibernate.ddl-auto=create-drop


teamverwaltung.db.driver=org.postgresql.Driver
teamverwaltung.db.url=jdbc:postgresql://localhost:5432/teamverwaltung
teamverwaltung.db.benutzer=teamverwaltung
teamverwaltung.db.passwort=pwd


spring.liquibase.enabled=true

server.servlet.session.cookie.same-site=strict